stages: 
- build
- test


build: 
  stage: build
  image: mcr.microsoft.com/java/jdk:11-zulu-ubuntu
  script: 
  - ./buildAndRun_remote.sh
  artifacts: 
    paths: 
    - ./program.jar

test: 
  stage: test
  image: mcr.microsoft.com/java/jdk:11-zulu-ubuntu
  script: 
    - ./buildAndRun_remote.sh
  
